# name: build
# on: [push]
# jobs:
#   build-release:
#     name: Release build
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions-rs/toolchain@v1
#         with:
#           toolchain: nightly
#       - uses: actions-rs/cargo@v1
#         with:
#           command: build
#           args: --release
