name: build

on: [push, pull_request]

env:
  rust_toolchain: nightly

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Remove `rust-toolchain.toml`
        run: rm rust-toolchain.toml

      - name: Setup
        uses: pulse-loop/esp32-rust-action@v1
          
      - name: Format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check
  
  clippy:
    name: Clippy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Remove `rust-toolchain.toml`
        run: rm rust-toolchain.toml

      - name: Setup
        uses: pulse-loop/esp32-rust-action@v1
      
      - name: Cache
        uses: actions/cache@v2
        with:
          path: target
          key: target

      - name: Clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --no-deps --target riscv32imc-esp-espidf -Zbuild-std=std,panic_abort -Zbuild-std-features=panic_immediate_abort -- -Dwarnings

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Remove `rust-toolchain.toml`
        run: rm rust-toolchain.toml

      - name: Setup
        uses: pulse-loop/esp32-rust-action@v1
      
      - name: Cache
        uses: actions/cache@v2
        with:
          path: target
          key: target
      
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target riscv32imc-esp-espidf -Zbuild-std=std,panic_abort -Zbuild-std-features=panic_immediate_abort
      
  examples:
    name: Build examples
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Remove `rust-toolchain.toml`
        run: rm rust-toolchain.toml

      - name: Setup
        uses: pulse-loop/esp32-rust-action@v1
      
      - name: Cache
        uses: actions/cache@v2
        with:
          path: target
          key: target

      - name: Build examples
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --examples --target riscv32imc-esp-espidf -Zbuild-std=std,panic_abort -Zbuild-std-features=panic_immediate_abort